name: colem # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '5.6' # just for humans, typically '1.2+git' or '1.3.2'
summary: Colecovision emulator
description: |
  Colecovision emulator

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  colem_icon.png
title: Colem

apps:
  colem:
    command: colem
parts:
  colem:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      colem: build/
      colem.1: man/man1/

architectures:
  - build-on: amd64

